const datas = [
    {
        key: 0,
        Category: 'Temperature',
        Standard: 'Kelvin',
        Datatypes: {
            'Kelvin': 'K',
            'Celsius': '°C',
            'Fahrenheit': '°F',
            'Rankine': '°R',
            'Reaumur': '°r',
        },



    },
    {
        key: 1,
        Category: 'Length',
        Standard: 'Meters',
        Datatypes: {
            'Meters': 'm',
            'Foot': 'ft',
            'Inch': 'in',
            'Kilometer': 'km',
            'Centimeter': 'cm',
            'Milimetre': 'mm',
            'Micrometers': 'µm',
            'Nanometers': 'nm',
            'Mile': 'mi',
            'Yard': 'yd',
            'Nautical mile': 'NM',
            'Decimeter': 'dm',
            'Fathom': 'ftm'
        },
        MetersMeters: ['+', 0],
        MetersFoot: ["*", 3.28084],
        MetersInch: ['*', 39.370079],
        MetersKilometer: ['/', 1000],
        MetersCentimeter: ['/', 0.01],
        MetersMilimetre: ['/', 0.001],
        MetersMicrometers: ['/', 1.0E-6],
        MetersNanometers: ['/', 1.0E-9],
        MetersMile: ['/', 1609.344],
        MetersYard: ['/', 0.9144],
        'MetersNautical mile': ['/', 1852],
        MetersDecimeter: ['/', 0.1],
        MetersFathom: ['/', 1.8288],

        KilometerMeters: ['*', 1000],
        CentimeterMeters: ['*', 0.01],
        MilimetreMeters: ['*', 0.001],
        MicrometersMeters: ['*', 1.0e-6],
        NanometersMeters: ['*', 1.0e-9],
        MileMeters: ['*', 1609.344],
        YardMeters: ['*', 0.9144],
        'Nautical mileMeters': ['*', 1852],
        DecimeterMeters: ['*', 0.1],
        FathomMeters: ['*', 1.8288],

        InchMeters: ['/', 39.370079],
        FootMeters: ["/", 3.28084],
    },
    {
        key: 2,
        Category: 'Mass',
        Standard: 'Kilograms',
        Datatypes: {
            'Kilograms': 'kg',
            'Grams': 'g',
            'Pounds': 'lb',
            'Tonne': 't',
            'Miligram': 'mg',
            'Microgram': 'µg',
            'Quintal': 'q',
            'Ounce': 'oz',
            'Stone(UK)': 'st',
            'Short ton(US)': 't',
            'Long ton(UK)': 't',
            'Carat': 'ct',
            'Grain': 'gr',


        },
        KilogramsKilograms: ['+', 0],
        KilogramsPounds: ['*', 2.20462262],
        KilogramsGrams: ['*', 1000],
        KilogramsTonne: ['/', 1000],

        'KilogramsMiligram': ['/', 1.0E-6],
        'KilogramsMicrogram': ['/', 1.0E-9],
        'KilogramsQuintal': ['/', 100],
        'KilogramsOunce': ['/', 0.0283495231],
        'KilogramsStone(UK)': ['/', 6.35029318],
        'KilogramsShort ton(US)': ['/', 907.18474],
        'KilogramsLong ton(UK)': ['/', 1016.0469088],
        'KilogramsCarat': ['/', 0.0002],
        'KilogramsGrain': ['/', 6.47989E-5],

        'MiligramKilograms': ['*', 1.0E-6],
        'MicrogramKilograms': ['*', 1.0E-9],
        'KilogramsQuintal': ['*', 100],
        'OunceKilograms': ['*', 0.0283495231],
        'Stone(UK)Kilograms': ['*', 6.35029318],
        'Short ton(US)Kilograms': ['*', 907.18474],
        'Long ton(UK)Kilograms': ['*', 1016.0469088],
        'CaratKilograms': ['*', 0.0002],
        'GrainKilograms': ['*', 6.47989E-5],
        PoundsKilograms: ['/', 2.20462262],
        GramsKilograms: ['/', 1000],
        TonneKilograms: ['*', 1000],

    },
    {
        key: 3,
        Category: 'Speed',
        Standard: 'Meter per second',
        Datatypes: {
            'Meter per second': 'm/s',
            'Meter per hour': 'm/h',
            'Kilometer per second': 'km/s',
            'Kilometer per hour': 'km/h',
            'Miles per hour': 'mph',
            'Foot per second': 'fps',
            'Inch per second': 'ips',
            'Knot': 'kn',
            'Mach': 'Ma',
            'Lightspeed': 'c',
        },
        'Meter per secondMeter per second': ['+', 0],

        'Meter per secondMeter per hour': ['/', 0.0002777778],
        'Meter per secondKilometer per second': ['/', 1000],
        'Meter per secondKilometer per hour': ['/', 0.2777777778],
        'Meter per secondMiles per hour': ['/', 0.44704],
        'Meter per secondFoot per second': ['/', 0.3048],
        'Meter per secondInch per second': ['/', 0.0254],
        'Meter per secondKnot': ['/', 0.5144444444],
        'Meter per secondMach': ['/', 340.29],
        'Meter per secondLightspeed': ['/', 299792458],

        'Meter per hourMeter per second': ['*', 0.0002777778],
        'Kilometer per secondMeter per second': ['*', 1000],
        'Kilometer per hourMeter per second': ['*', 0.2777777778],
        'Miles per hourMeter per second': ['*', 0.44704],
        'Foot per secondMeter per second': ['*', 0.3048],
        'Inch per secondMeter per second': ['*', 0.0254],
        'KnotMeter per second': ['*', 0.5144444444],
        'MachMeter per second': ['*', 340.29],
        'LightspeedMeter per second': ['*', 299792458],



    },
    {
        key: 4,
        Category: 'Time',
        Standard: 'Second',
        Datatypes: {
            'Second': 's',
            'Nanosecond': 'ns',
            'Microsecond': 'µm',
            'Milisecond': 'ms',
            'Minute': 'min',
            'Hour': 'h',
            'Day': 'd',
            'Week': 'wk',
            'Month': 'm',
            'Year': 'y',
            'Decade': '',
            'Century': '',
            'Millennium':''


        },
        'SecondSecond': ['+', 0],
        
        'SecondNanosecond': ['/',1.0E-9  ],
        'SecondMicrosecond': ['/',1.0E-6  ],
        'SecondMilisecond': ['/',0.001   ],
        'SecondMinute': ['/',60  ],
        'SecondHour':['/', 3600 ],
        'SecondDay': ['/',  86400],
        'SecondWeek': ['/',  604800],
        'SecondMonth': ['/', 2628000 ],
        'SecondYear': ['/',  31536000  ],
        'SecondDecade': ['/',315360000  ],
        'SecondCentury': ['/', 3153600000 ],
        'SecondMillennium': ['/', 31536000000 ],

        'NanosecondSecond': ['*',1.0E-9  ],
        'MicrosecondSecond': ['*',1.0E-6  ],
        'MilisecondSecond': ['*',0.001   ],
        'MinuteSecond': ['*',60  ],
        'HourSecond':['*', 3600 ],
        'DaySecond': ['*',  86400],
        'WeekSecond': ['*',  604800],
        'MonthSecond': ['*', 2628000 ],
        'YearSecond': ['*',  31536000  ],
        'DecadeSecond': ['*',315360000  ],
        'CenturySecond': ['*', 3153600000 ],
        'MillenniumSecond': ['*', 31536000000 ],



    },



];
export default datas;